config/routes.rb
Rails.application.routes.draw do

  root 'wines#index'
  get '/wine_review' => 'wines#index', as: 'wines'
  get '/wine_review/new' => 'wines#new', as: 'new_wine'
  get '/wine_review/:id' => 'wines#show', as: 'wine'
  post '/wine_review' => 'wines#create'
  patch '/wine_review/:id' => 'wines#update'
  delete '/wine_review/:id' => 'wines#destroy'

  resources :wines do
    resources :log_entries
    get 'page/:page', :action => :index, :on => :collection
  end

end

app/models/log_entry.rb
class LogEntry < ActiveRecord::Base
  belongs_to :wine
  RATING = [1..5]
  validates :name, :rating, :location, :comments, :tasted_on, presence: true
  validates :comments, length: { minimum: 15 }, unless: 'comments.blank?'
  validates :rating, inclusion: { in: RATING, message: "must be from #{RATING.first} to #{RATING.last}" }

end

app/models/wine.rb
class Wine < ActiveRecord::Base
  has_many :log_entries, dependent: :destroy

  def average_rating
    if log_entries.loaded?
      log_entries.map(&:rating).compact.average
    else
      log_entries.average(:rating)
    end
  end

  VARIETALS = ['Barbera', 'Cabernet Sauvignon', 'Champagne/Sparkling Wine', 'Chardonnay', 'Chenin Blanc', 'Dolcetto', 'Fume Blanc', 'Gewürztraminer', 'Merlot', 'Mourvedre', 'Petite Sirah', 'Pinot Grigio', 'Pinot Noir', 'Riesling', 'Rosés', 'Sangiovese',  'Sauvignon Blanc', 'Syrah', 'Viognier', 'Zinfandel']
  validates :name, :winery, :country, :year, :varietal, presence: true
  validates :year,
    numericality: { only_integer: true, greater_than_or_equal_to: 0 },
    unless: "year.blank?"
  validates :varietal, inclusion: { in: VARIETALS }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # Don't apply layouts for ajax requests
  layout ->(controller) { controller.request.xhr? ? false : 'application' }
end

app/controllers/labelling_form_builder.rb
class LabellingFormBuilder < ActionView::Helpers::FormBuilder
  def text_field(attribute, options={})
    label(attribute) + super
  end
end

app/controllers/log_entries_controller.rb
class LogEntriesController < ApplicationController
  before_action :set_wine

  def index
    @log_entries = @wine.log_entries.order('created_at desc')
  end

  def new
    @log_entry = @wine.log_entry.new
  end

  def create
    @log_entry = @wine.log_entry.new(log_entry_params)
    if @log_entry.save
      redirect_to wine_log_entries_path(@wine), notice: 'Log Entry saved!'
    else
      render :new
    end
  end

  private

  def set_wine
    @wine = Wine.find(params[:wine_id])
  end

  def log_entry_params
    params.require(:log_entry).permit(:wine_id, :rating, :name, :comments, :location, :tasted_on)
  end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine,
                only: [ :show, :edit, :update, :destroy ]

  def index
    @available_at = Time.now
    @wines = Wine.includes(:log_entries).order(:name).page(params[:page])
  end

  def show; end

  def new
    @wine = Wine.new
  end

  def create
    @wine= Book.new(book_params)
    if @wine.save
      redirect_to @wine, notice: "#{@wine.name} was created!"
    else
      render :new
    end
  end

  def update
    if @wine.update(wine_params)
      redirect_to @wine, notice: "#{@wine.name} was updated!"
    else
      render :edit
    end
  end

  def destroy
    @wine.destroy
    redirect_to wines_url
  end

  private

  def wine_params
    params.require(:wine).permit(:name, :winery, :country, :average_rating, :year, :varietal)
  end

  def set_wine
    @wine = Wine.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/log_entries_helper.rb
module LogEntriesHelper
end

app/helpers/wines_helper.rb
module WinesHelper
  def formatted_time(time)
    time.strftime("%B %d, %Y at %l:%M %p")
  end
  def format_average_rating(wine)
    average = wine.average_rating
    if average
      pluralize(number_with_precision(average, precision: 1), 'rating')
    else
      'No log entries'
    end
  end
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <h3 class="text-center text-muted">For Educational Uses Only</h3>
  </div>
</nav>

app/views/layouts/_header.html.erb
<header class="page-header">
<h1><%= link_to('Amazing Wines', root_path) %></h1>
</header>

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Navigation</h3>
    </div>
    <div class="panel-body">
      <p>
        <%= link_to 'All Wines', wines_path %>
      </p>
      <p>
        <%= link_to 'Create Wine', new_wine_path %>
      </p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Amazing Wines<%= yield :title %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render '/layouts/header' %>
  </div>
  <div class="container">
    <div class="col-xs-9">
      <%= render '/shared/flashes' %>
      <%= yield %>
    </div>
    <div class="col-xs-3">
      <%= render '/layouts/sidebar' %>
    </div>
  </div>
  <%= render '/layouts/footer' %>
</body>
</html>

app/views/log_entries/_form.html.erb
<%= form_for( [ @wine, @log_entry ] ) do |f| %>
  <%= render 'shared/validation_errors', object: @log_entry %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true, placeholder: 'Name' %><br/>
  <%= f.label :location %>
  <%= f.text_field :location %><br/>
  <%= f.label :rating %>
  <% LogEntry::RATING.each do |s| %>
    <%= f.radio_button :rating, s %> <%= s %>
  <% end %><br />
  <%= f.label :comment %><br/>
  <%= f.text_area :comments %><br/>
  <p>
    <%= f.submit %>
    <%= link_to 'Cancel', wine_log_entry_path(@wine), id: 'cancel_wine' %>
  </p>
<% end %>

app/views/log_entries/index.html.erb
<header>Log Entries for <%= link_to(@wine.name, @wine) %></header>
<ol id="log_entries">
  <% @log_entries.each do |log_entry| %>
    <li>
      <span class="log_entry"><%= log_entry.rating %></span>
      <span class="name">by <%= log_entry.name %> </span>
      <span class="date">
        <%= time_ago_in_words(log_entry.created_at) %> ago
      </span>
      <p>
        &quot;<%= log_entry.comments %>&quot;
      </p>
    </li>
  <% end %>
</ol>
<%= link_to 'Write a Log Entry', new_wine_log_entry_path(@wine),
        remote: true,
        data: { 'update-target' => 'log_entry_form_container' },
        class: 'btn btn-primary' %>

<div id="log_entry_form_container"></div>

app/views/log_entries/new.html.erb
<h1>Write a log entry for <%= @wine.name %></h1>
<%= render 'form' %>

app/views/shared/_flashes.html.erb
<% if flash.present? %>
  <div id="flashes">
    <% flash.each do |key, value| %>
      <p class="flash <%= key %>"><%= value %></p>
    <% end %>
  </div>
<% end %>

app/views/shared/_validation_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    Oops! The <%= object.class.name.humanize.downcase %> could not be saved.<br />
    Correct the following <%= pluralize(object.errors.count, "error") %>:
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/named _validation_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    Oops! The <%= object.class.name.humanize.downcase %> could not be saved.<br />
    Correct the following <%= pluralize(object.errors.count, "error") %>:
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/wines/_form.html.erb
<%= form_for(@wine) do |f| %>
  <%= render 'shared/validation_errors', object: @wine %>
  <table>
    <tr>
      <td><%= f.label :Wine %></td>
      <td><%= f.text_field :name, autofocus: true %></td>
    </tr>
    <tr>
      <td><%= f.label :Winery %></td>
      <td><%= f.text_field :winery %></td>
    </tr>
    <tr>
      <td><%= f.label :Year %></td>
      <td><%= f.text_field :year %></td>
    </tr>
    <tr>
      <td><%= f.label :Varietal %></td>
      <td><%= f.select :varietal, Wine::VARIETALS, { prompt: "Pick one" } %></td>
    </tr>
    <tr>
      <td><%= f.label :Country %></td>
      <td><%= f.text_field :country %></td>
    </tr>
  </table>
  <p>
    <%= f.submit "Save" %>
    <%= link_to "Cancel", wines_path %>
  </p>
<% end %>

app/views/wines/edit.html.erb
<h1>Editing Wine <%= @wine.name %></h1>
<%= render 'form' %>

app/views/wines/index.html.erb
<h3>Available as of <%= formatted_time(@available_at) %> </h3>
<%= page_entries_info @wines %>
<br/>
<br/>
<table>
  <tr>
    <td>Name</td>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
    <td>Winery</td>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
  </tr>
  <% @wines.each do |wine| %>
  <tr>
    <td><%= wine.name %></td>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
    <td><%= wine.winery %></td>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
    <td><%= format_average_rating(wine) %>
        <% if log_entry.any? %>
    (out of <%= pluralize(wine.log_entries.size, 'log entry') %>)
  <% end %>
    <td><%= button_to("Show", wine, method: :get) %></td>
    <td><%= button_to("Edit", edit_wine_path(wine), method: :get) %></td>
    <td><%= button_to "Delete", wine, method: :delete, data: { confirm: "Are you sure?" } %></td>
  </tr>
  <% end %>
</table>
<%= paginate @wines %>

app/views/wines/new.html.erb
<h1>Add Wine</h1>
<%= render 'form' %>

app/views/wines/show.html.erb
<article class="wine">
  <% content_for :title, @wine.name %>
  <header>
    <h2><%= @wine.name %></h2>
  </header>
  <p><label>Year:</label> <%= @wine.year %></p>
  <p><label>Winery:</label> <%= @wine.winery %></p>
  <p><label>Country:</label> <%= @wine.country  %></p>
  <p><label>Varietal:</label> <%= @wine.varietal %></p>
  <table>
    <tr>
      <td><%= button_to("Edit", edit_wine_path(@wine), method: :get) %></td>
      <td><%= button_to "Delete", @wine, method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>
  </table>
  <br/>
  <p>
    Read all
    <%= link_to pluralize(@wine.log_entries.size, 'log entry'),
                          wine_log_entries_path(@wine) %>
  </p>
  <p><label>Average Rating:</label> <%= format_average_rating(@wine) %></p>
</article>